FROM python:3.12.1-alpine

WORKDIR /app

ADD requirements.txt /app/requirements.txt

RUN apk add gcc musl-dev && python3 -m pip install -r requirements.txt

ADD . /app/

ENV FLASK_APP=src/app.py
ENV FLASK_ENV=development


CMD flask run --host=0.0.0.0

EXPOSE 3000